using CarPosAPI.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CarPosAPI.Data.Configurations;

/// <summary>
/// EF mapping for <see cref="DeviceEvent"/>. Explicit snake_case names, as everywhere
/// else in this schema. The CHECK constraints are what turn the three text columns into
/// closed vocabularies: <see cref="Services.Ingest.DeviceStatusValidator"/> refuses
/// anything else politely, and the database refuses it absolutely — including the
/// pairing of each kind with only its own reasons, so an "offline / crash" row cannot
/// exist even if a future writer tried to make one.
/// </summary>
public sealed class DeviceEventConfiguration : IEntityTypeConfiguration<DeviceEvent>
{
    /// <summary>Longest kind name ("restart"), with room to spare.</summary>
    private const int KindMaxLength = 16;

    /// <summary>Longest reason name ("connectionLost"), with room to spare.</summary>
    private const int ReasonMaxLength = 24;

    /// <summary>Longest severity name ("normal"), with room to spare.</summary>
    private const int SeverityMaxLength = 8;

    /// <summary>The firmware's detail codes are <c>[a-z0-9_]{1,32}</c>.</summary>
    public const int DetailMaxLength = 32;

    /// <summary>Configures the device_events table.</summary>
    /// <param name="builder">Type builder supplied by EF Core.</param>
    public void Configure(EntityTypeBuilder<DeviceEvent> builder)
    {
        builder.ToTable("device_events", table =>
        {
            table.HasCheckConstraint(
                "ck_device_events_kind",
                "kind IN ('offline', 'restart')");
            table.HasCheckConstraint(
                "ck_device_events_reason",
                "(kind = 'offline' AND reason IN ('sleep', 'powerOff', 'batteryLow', 'error', 'connectionLost'))"
                + " OR (kind = 'restart' AND reason IN ('powerOn', 'powerLoss', 'crash'))");
            table.HasCheckConstraint(
                "ck_device_events_severity",
                "severity IN ('normal', 'alert', 'error')");
            // Nullable columns: the CHECK only bites a value that is present.
            table.HasCheckConstraint(
                "ck_device_events_battery_pct",
                "battery_pct >= 0 AND battery_pct <= 100");
            table.HasCheckConstraint(
                "ck_device_events_sleep_seconds",
                $"sleep_seconds >= 0 AND sleep_seconds <= {Dtos.DeviceConfigRules.MaxIntervalSeconds}");
        });

        builder.HasKey(deviceEvent => deviceEvent.Id);

        // long key → bigint GENERATED BY DEFAULT AS IDENTITY (Npgsql default).
        builder.Property(deviceEvent => deviceEvent.Id)
            .HasColumnName("id");

        builder.Property(deviceEvent => deviceEvent.DeviceId)
            .HasColumnName("device_id")
            .IsRequired();

        // History, like positions: deleting a device must not cascade it away. The two
        // GDPR erasure paths delete these rows explicitly, before the device.
        builder.HasOne(deviceEvent => deviceEvent.Device)
            .WithMany()
            .HasForeignKey(deviceEvent => deviceEvent.DeviceId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.Property(deviceEvent => deviceEvent.ReceivedAt)
            .HasColumnName("received_at")
            .HasDefaultValueSql("now()")
            .IsRequired();

        builder.Property(deviceEvent => deviceEvent.DeviceTime)
            .HasColumnName("device_time");

        builder.Property(deviceEvent => deviceEvent.Kind)
            .HasColumnName("kind")
            .HasMaxLength(KindMaxLength)
            .IsRequired();

        builder.Property(deviceEvent => deviceEvent.Reason)
            .HasColumnName("reason")
            .HasMaxLength(ReasonMaxLength)
            .IsRequired();

        builder.Property(deviceEvent => deviceEvent.Severity)
            .HasColumnName("severity")
            .HasMaxLength(SeverityMaxLength)
            .IsRequired();

        builder.Property(deviceEvent => deviceEvent.BatteryPct)
            .HasColumnName("battery_pct");

        builder.Property(deviceEvent => deviceEvent.SleepSeconds)
            .HasColumnName("sleep_seconds");

        builder.Property(deviceEvent => deviceEvent.Detail)
            .HasColumnName("detail")
            .HasMaxLength(DetailMaxLength);

        // Every read is "this device, newest first, maybe a time range" — the Events
        // tab, the badge's latest-offline subquery, and both erasure paths.
        builder.HasIndex(deviceEvent => new { deviceEvent.DeviceId, deviceEvent.ReceivedAt })
            .HasDatabaseName("ix_device_events_device_id_received_at");
    }
}
