using CarPosAPI.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CarPosAPI.Data.Configurations;

/// <summary>
/// EF mapping for <see cref="Position"/>. Explicit snake_case names for the same
/// reason as <see cref="DeviceConfiguration"/> (raw ingest SQL depends on them).
/// The CHECK constraints mirror <see cref="Services.Ingest.PositionValidator"/> —
/// the validator rejects bad data politely, the database refuses it absolutely,
/// so even a future buggy writer cannot store impossible coordinates.
/// </summary>
public sealed class PositionConfiguration : IEntityTypeConfiguration<Position>
{
    /// <summary>Configures the positions table.</summary>
    /// <param name="builder">Type builder supplied by EF Core.</param>
    public void Configure(EntityTypeBuilder<Position> builder)
    {
        builder.ToTable("positions", table =>
        {
            table.HasCheckConstraint("ck_positions_latitude", "latitude >= -90 AND latitude <= 90");
            table.HasCheckConstraint("ck_positions_longitude", "longitude >= -180 AND longitude <= 180");
            table.HasCheckConstraint("ck_positions_speed_kmph", "speed_kmph >= 0 AND speed_kmph <= 1000");
            table.HasCheckConstraint("ck_positions_altitude_m", "altitude_m >= -500 AND altitude_m <= 10000");
            // Optional sensor columns: nullable, so the CHECK only bites a value
            // that is actually present (a NULL makes the predicate unknown, which
            // passes). Bounds mirror the validator: battery 0–100, accel ±16 g.
            table.HasCheckConstraint("ck_positions_battery_pct", "battery_pct >= 0 AND battery_pct <= 100");
            table.HasCheckConstraint("ck_positions_accel_x_g", "accel_x_g >= -16 AND accel_x_g <= 16");
            table.HasCheckConstraint("ck_positions_accel_y_g", "accel_y_g >= -16 AND accel_y_g <= 16");
            table.HasCheckConstraint("ck_positions_accel_z_g", "accel_z_g >= -16 AND accel_z_g <= 16");
            table.HasCheckConstraint("ck_positions_temperature_c", "temperature_c >= -40 AND temperature_c <= 125");
        });

        builder.HasKey(position => position.Id);

        // long key → bigint GENERATED BY DEFAULT AS IDENTITY (Npgsql default).
        builder.Property(position => position.Id)
            .HasColumnName("id");

        builder.Property(position => position.DeviceId)
            .HasColumnName("device_id")
            .IsRequired();

        // Positions are history; deleting a device must not cascade away its trail.
        builder.HasOne(position => position.Device)
            .WithMany()
            .HasForeignKey(position => position.DeviceId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.Property(position => position.FixTime)
            .HasColumnName("fix_time")
            .IsRequired();

        builder.Property(position => position.ReceivedAt)
            .HasColumnName("received_at")
            .HasDefaultValueSql("now()");

        builder.Property(position => position.Latitude)
            .HasColumnName("latitude")
            .IsRequired();

        builder.Property(position => position.Longitude)
            .HasColumnName("longitude")
            .IsRequired();

        builder.Property(position => position.SpeedKmph)
            .HasColumnName("speed_kmph")
            .IsRequired();

        builder.Property(position => position.AltitudeMeters)
            .HasColumnName("altitude_m")
            .IsRequired();

        // Optional sensor columns — nullable, absent on older fixes and on
        // devices with the sensor disabled.
        builder.Property(position => position.BatteryPct)
            .HasColumnName("battery_pct");

        builder.Property(position => position.AccelXG)
            .HasColumnName("accel_x_g");

        builder.Property(position => position.AccelYG)
            .HasColumnName("accel_y_g");

        builder.Property(position => position.AccelZG)
            .HasColumnName("accel_z_g");

        builder.Property(position => position.TemperatureC)
            .HasColumnName("temperature_c");

        // The dedupe arbiter: MQTT delivery is at-least-once and backlog replays
        // carry no markers, so (device, fix time) is the only identity of a fix.
        // ON CONFLICT DO NOTHING in the writer targets exactly these columns.
        // Doubles as the read index for future "device + time range" queries.
        builder.HasIndex(position => new { position.DeviceId, position.FixTime })
            .IsUnique()
            .HasDatabaseName("ux_positions_device_id_fix_time");
    }
}
