// <auto-generated />
using System;
using CarPosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarPosAPI.Data.Migrations
{
    [DbContext(typeof(CarPosDbContext))]
    [Migration("20260719141250_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarPosAPI.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<byte[]>("PrivateKeyCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("private_key_ciphertext");

                    b.Property<string>("PublicKeyPem")
                        .HasColumnType("text")
                        .HasColumnName("public_key_pem");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ux_devices_device_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AltitudeMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude_m");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("FixTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fix_time");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("SpeedKmph")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_kmph");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "FixTime")
                        .IsUnique()
                        .HasDatabaseName("ux_positions_device_id_fix_time");

                    b.ToTable("positions", null, t =>
                        {
                            t.HasCheckConstraint("ck_positions_altitude_m", "altitude_m >= -500 AND altitude_m <= 10000");

                            t.HasCheckConstraint("ck_positions_latitude", "latitude >= -90 AND latitude <= 90");

                            t.HasCheckConstraint("ck_positions_longitude", "longitude >= -180 AND longitude <= 180");

                            t.HasCheckConstraint("ck_positions_speed_kmph", "speed_kmph >= 0 AND speed_kmph <= 1000");
                        });
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.Position", b =>
                {
                    b.HasOne("CarPosAPI.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
