// <auto-generated />
using System;
using CarPosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarPosAPI.Data.Migrations
{
    [DbContext(typeof(CarPosDbContext))]
    [Migration("20260827111713_AddDeviceConfigSchedules")]
    partial class AddDeviceConfigSchedules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarPosAPI.Data.Entities.Access", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_delete");

                    b.Property<bool>("CanModifySettings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_modify_settings");

                    b.Property<bool>("CanRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_read");

                    b.Property<bool>("CanShare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_share");

                    b.Property<DateTime>("DateRegistration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_registration")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int>("GrantedBy")
                        .HasColumnType("integer")
                        .HasColumnName("granted_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_accesses_device_id");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ux_accesses_user_id_device_id_active")
                        .HasFilter("is_active");

                    b.ToTable("accesses", (string)null);
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AckPublicKeyPem")
                        .HasColumnType("text")
                        .HasColumnName("ack_public_key_pem");

                    b.Property<DateTime?>("ConfigAppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("config_applied_at");

                    b.Property<int?>("ConfigAppliedVersion")
                        .HasColumnType("integer")
                        .HasColumnName("config_applied_version");

                    b.Property<DateTime?>("ConfigOverrideUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("config_override_until");

                    b.Property<bool>("ConfigScheduleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("config_schedule_enabled");

                    b.Property<DateTime?>("ConfigScheduleEvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("config_schedule_evaluated_at");

                    b.Property<Guid?>("ConfigScheduleFallbackProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("config_schedule_fallback_profile_id");

                    b.Property<int>("ConfigVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("config_version");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<byte[]>("PrivateKeyCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("private_key_ciphertext");

                    b.Property<string>("PublicKeyPem")
                        .HasColumnType("text")
                        .HasColumnName("public_key_pem");

                    b.HasKey("Id");

                    b.HasIndex("ConfigScheduleFallbackProfileId");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ux_devices_device_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.DeviceAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("alias");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ux_device_aliases_user_id_device_id");

                    b.ToTable("device_aliases", (string)null);
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.DeviceConfigProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ConfigCheckSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("config_check_s");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int>("FixTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("fix_timeout_s");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_s");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<int>("QueueMaxFixes")
                        .HasColumnType("integer")
                        .HasColumnName("queue_max_fixes");

                    b.Property<int>("RetryIntervalHours")
                        .HasColumnType("integer")
                        .HasColumnName("retry_interval_h");

                    b.Property<int>("RetryMaxAgeHours")
                        .HasColumnType("integer")
                        .HasColumnName("retry_max_age_h");

                    b.Property<bool>("SleepBetween")
                        .HasColumnType("boolean")
                        .HasColumnName("sleep_between");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeviceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_device_config_profiles_device_id_name");

                    b.ToTable("device_config_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_device_config_profiles_config_check_s", "config_check_s BETWEEN 60 AND 86400");

                            t.HasCheckConstraint("ck_device_config_profiles_fix_timeout_s", "fix_timeout_s BETWEEN 15 AND 3600");

                            t.HasCheckConstraint("ck_device_config_profiles_interval_s", "interval_s BETWEEN 5 AND 86400");

                            t.HasCheckConstraint("ck_device_config_profiles_queue_max_fixes", "queue_max_fixes BETWEEN 100 AND 100000");

                            t.HasCheckConstraint("ck_device_config_profiles_retry_interval_h", "retry_interval_h BETWEEN 1 AND 720");

                            t.HasCheckConstraint("ck_device_config_profiles_retry_max_age_h", "retry_max_age_h BETWEEN 0 AND 8760");
                        });
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.DeviceConfigScheduleRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DaysMaskUtc")
                        .HasColumnType("integer")
                        .HasColumnName("days_mask_utc");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("priority");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("StartMinuteUtc")
                        .HasColumnType("integer")
                        .HasColumnName("start_minute_utc");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_config_schedule_rules_device_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_device_config_schedule_rules_profile_id");

                    b.ToTable("device_config_schedule_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_device_config_schedule_rules_days_mask", "days_mask_utc BETWEEN 1 AND 127");

                            t.HasCheckConstraint("ck_device_config_schedule_rules_duration", "duration_minutes BETWEEN 1 AND 1440");

                            t.HasCheckConstraint("ck_device_config_schedule_rules_priority", "priority BETWEEN 0 AND 1000");

                            t.HasCheckConstraint("ck_device_config_schedule_rules_start_minute", "start_minute_utc BETWEEN 0 AND 1439");
                        });
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.DeviceConfigVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ConfigCheckSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3600)
                        .HasColumnName("config_check_s");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int>("FixTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("fix_timeout_s");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_s");

                    b.Property<int>("QueueMaxFixes")
                        .HasColumnType("integer")
                        .HasColumnName("queue_max_fixes");

                    b.Property<int>("RetryIntervalHours")
                        .HasColumnType("integer")
                        .HasColumnName("retry_interval_h");

                    b.Property<int>("RetryMaxAgeHours")
                        .HasColumnType("integer")
                        .HasColumnName("retry_max_age_h");

                    b.Property<bool>("SleepBetween")
                        .HasColumnType("boolean")
                        .HasColumnName("sleep_between");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_profile_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SourceProfileId");

                    b.HasIndex("DeviceId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_device_config_versions_device_id_version");

                    b.ToTable("device_config_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_device_config_versions_config_check_s", "config_check_s BETWEEN 60 AND 86400");

                            t.HasCheckConstraint("ck_device_config_versions_fix_timeout_s", "fix_timeout_s BETWEEN 15 AND 3600");

                            t.HasCheckConstraint("ck_device_config_versions_interval_s", "interval_s BETWEEN 5 AND 86400");

                            t.HasCheckConstraint("ck_device_config_versions_queue_max_fixes", "queue_max_fixes BETWEEN 100 AND 100000");

                            t.HasCheckConstraint("ck_device_config_versions_retry_interval_h", "retry_interval_h BETWEEN 1 AND 720");

                            t.HasCheckConstraint("ck_device_config_versions_retry_max_age_h", "retry_max_age_h BETWEEN 0 AND 8760");

                            t.HasCheckConstraint("ck_device_config_versions_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AccelXG")
                        .HasColumnType("double precision")
                        .HasColumnName("accel_x_g");

                    b.Property<double?>("AccelYG")
                        .HasColumnType("double precision")
                        .HasColumnName("accel_y_g");

                    b.Property<double?>("AccelZG")
                        .HasColumnType("double precision")
                        .HasColumnName("accel_z_g");

                    b.Property<double>("AltitudeMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude_m");

                    b.Property<int?>("BatteryPct")
                        .HasColumnType("integer")
                        .HasColumnName("battery_pct");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("FixTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fix_time");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("SpeedKmph")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_kmph");

                    b.Property<double?>("TemperatureC")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature_c");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "FixTime")
                        .IsUnique()
                        .HasDatabaseName("ux_positions_device_id_fix_time");

                    b.ToTable("positions", null, t =>
                        {
                            t.HasCheckConstraint("ck_positions_accel_x_g", "accel_x_g >= -16 AND accel_x_g <= 16");

                            t.HasCheckConstraint("ck_positions_accel_y_g", "accel_y_g >= -16 AND accel_y_g <= 16");

                            t.HasCheckConstraint("ck_positions_accel_z_g", "accel_z_g >= -16 AND accel_z_g <= 16");

                            t.HasCheckConstraint("ck_positions_altitude_m", "altitude_m >= -500 AND altitude_m <= 10000");

                            t.HasCheckConstraint("ck_positions_battery_pct", "battery_pct >= 0 AND battery_pct <= 100");

                            t.HasCheckConstraint("ck_positions_latitude", "latitude >= -90 AND latitude <= 90");

                            t.HasCheckConstraint("ck_positions_longitude", "longitude >= -180 AND longitude <= 180");

                            t.HasCheckConstraint("ck_positions_speed_kmph", "speed_kmph >= 0 AND speed_kmph <= 1000");

                            t.HasCheckConstraint("ck_positions_temperature_c", "temperature_c >= -40 AND temperature_c <= 125");
                        });
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.Access", b =>
                {
                    b.HasOne("CarPosAPI.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarPosAPI.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.Device", b =>
                {
                    b.HasOne("CarPosAPI.Data.Entities.DeviceConfigProfile", null)
                        .WithMany()
                        .HasForeignKey("ConfigScheduleFallbackProfileId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.DeviceAlias", b =>
                {
                    b.HasOne("CarPosAPI.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarPosAPI.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.DeviceConfigProfile", b =>
                {
                    b.HasOne("CarPosAPI.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarPosAPI.Data.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.DeviceConfigScheduleRule", b =>
                {
                    b.HasOne("CarPosAPI.Data.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarPosAPI.Data.Entities.DeviceConfigProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.DeviceConfigVersion", b =>
                {
                    b.HasOne("CarPosAPI.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarPosAPI.Data.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarPosAPI.Data.Entities.DeviceConfigProfile", null)
                        .WithMany()
                        .HasForeignKey("SourceProfileId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CarPosAPI.Data.Entities.Position", b =>
                {
                    b.HasOne("CarPosAPI.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
