namespace CarPosAPI.Data.Entities;

/// <summary>
/// A temporary, account-less window onto one device's positions: a link that is
/// hard to guess, gated by a separate code, alive only between two instants the
/// creator picked, and revocable at any moment.
///
/// <para>
/// It sits <em>beside</em> <see cref="Access"/> rather than inside it, and that
/// separation is deliberate. An <see cref="Access"/> row answers "what may this
/// account do with this device" and is resolved through
/// <see cref="Services.Authorization.IDeviceAccessAuthorizer"/> for every
/// authenticated request. A share link answers a different question — "may this
/// anonymous visitor see these coordinates, right now" — and is resolved by
/// <see cref="Services.Sharing.IShareViewService"/> along a code path that never
/// takes a user id. Keeping the two apart is what guarantees a share can never be
/// mistaken for an account, or widened into one.
/// </para>
///
/// <para>
/// <b>Two secrets guard it, and neither can be recovered from this row.</b> The
/// link carries <c>selector.verifier</c>: <see cref="Selector"/> is stored in the
/// clear because it is only a lookup key, while the verifier survives here as
/// nothing but a SHA-256 digest, and the human-typed code as a PBKDF2 hash. A
/// database dump therefore yields no working link — which is the point of storing
/// them differently rather than trusting one long secret.
/// </para>
///
/// Mapped by <see cref="Configurations.ShareLinkConfiguration"/>.
/// </summary>
public sealed class ShareLink
{
    /// <summary>
    /// Surrogate key, and the value carried in the share token's <c>share</c>
    /// claim. A Guid rather than an int precisely because it travels in a token:
    /// a sequential id would let a holder of one share reason about how many
    /// others exist and when they were made.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Public half of the link secret — Base64Url of 16 random bytes, unique.
    ///
    /// Stored in the clear on purpose: it is an identifier, not a credential, and
    /// it has to be looked up by equality. Splitting the token this way is what
    /// lets the lookup use an index while the half that actually authorises
    /// (<see cref="VerifierHash"/>) is never stored in a usable form. Hashing this
    /// half too would buy nothing and cost the index.
    /// </summary>
    public string Selector { get; set; } = string.Empty;

    /// <summary>
    /// Base64 of SHA-256 over the 32-byte verifier — the half of the link that
    /// authorises.
    ///
    /// A plain hash rather than PBKDF2, and that is a considered choice rather
    /// than an oversight: the verifier is 256 bits straight out of
    /// <c>RandomNumberGenerator</c>, so there is no dictionary for an attacker to
    /// work through and nothing for key stretching to slow down. Stretching it
    /// would only tax every redeem. The <em>passphrase</em> is the low-entropy
    /// secret, and it is the one that gets PBKDF2.
    /// </summary>
    public string VerifierHash { get; set; } = string.Empty;

    /// <summary>
    /// The visitor's code, hashed with the same Identity PBKDF2 hasher that
    /// protects account passwords (<see cref="Services.Auth.IPasswordHasher"/>).
    /// Generated by the server, shown to the creator exactly once, and never
    /// recoverable from here.
    /// </summary>
    public string PassphraseHash { get; set; } = string.Empty;

    /// <summary>
    /// The device being shared — the internal <see cref="Device.Id"/> Guid, never
    /// the MQTT identity.
    /// </summary>
    public Guid DeviceId { get; set; }

    /// <summary>Navigation to the shared device.</summary>
    public Device? Device { get; set; }

    /// <summary>
    /// Who created the link, kept for audit ("who handed this out?").
    ///
    /// <b>Nullable for the same reason as <see cref="Access.GrantedBy"/>:</b> an
    /// account erased under Art. 17 must be unlinkable from records that outlive
    /// it. In practice erasure deletes this account's links outright — nobody else
    /// can administer them — but the column stays nullable so the erasure service
    /// has the option, and so the two sharing tables behave alike.
    /// </summary>
    public int? CreatedByUserId { get; set; }

    /// <summary>
    /// What the visitor sees the tracker called, and the creator's own note about
    /// who the link was for.
    ///
    /// It doubles as a privacy control: the visitor never learns the device's
    /// <see cref="Device.DeviceId"/> (the case-sensitive MQTT topic name) and need
    /// not learn its real <see cref="Device.DisplayName"/> either. Defaults to the
    /// display name when the creator does not set one.
    /// </summary>
    public string Label { get; set; } = string.Empty;

    /// <summary>
    /// Start of the window (UTC). Before this the link answers "not yet active",
    /// and no position from before it is ever visible.
    /// </summary>
    public DateTime ValidFrom { get; set; }

    /// <summary>
    /// End of the window (UTC). <b>One window, used twice:</b> it bounds when the
    /// link works and, independently enforced, which fixes it can return. That is
    /// what makes "they could only ever see Tuesday afternoon" a property of the
    /// database rather than of the frontend asking nicely.
    /// </summary>
    public DateTime ValidUntil { get; set; }

    /// <summary>How much history the link exposes.</summary>
    public ShareScope Scope { get; set; } = ShareScope.LatestOnly;

    /// <summary>Whether speed travels with each fix. Off by default.</summary>
    public bool IncludeSpeed { get; set; }

    /// <summary>
    /// Whether battery and temperature travel with each fix. Off by default —
    /// they say nothing about location and quite a lot about the vehicle.
    /// </summary>
    public bool IncludeTelemetry { get; set; }

    /// <summary>
    /// When the creator revoked the link, or null while it stands.
    ///
    /// Revocation is a soft stamp, like every other deactivation in this schema:
    /// the row survives so "this link existed, and was withdrawn at this time"
    /// stays answerable. Because every request re-reads this column, setting it
    /// stops access on the very next call rather than whenever a token expires.
    /// </summary>
    public DateTime? RevokedAt { get; set; }

    /// <summary>
    /// Consecutive wrong-code attempts since the last success. Drives
    /// <see cref="LockedUntil"/>, and is shown to the creator so a link being
    /// worked on is visible rather than silent.
    /// </summary>
    public int FailedAttempts { get; set; }

    /// <summary>
    /// While set and in the future, the link refuses codes outright. Grows with
    /// <see cref="FailedAttempts"/> so guessing gets slower, and clears on the
    /// next success so a recipient who simply fumbled is not punished for it.
    /// </summary>
    public DateTime? LockedUntil { get; set; }

    /// <summary>How many times the code was entered correctly. Creator-visible.</summary>
    public int SuccessfulRedeems { get; set; }

    /// <summary>
    /// When the link was last opened successfully, or null if never.
    ///
    /// This and the two counters are the whole audit trail, on purpose. Recording
    /// the visitor's address or user agent would mean collecting personal data
    /// about a third party who never agreed to anything, to answer a question
    /// these three columns already answer.
    /// </summary>
    public DateTime? LastAccessedAt { get; set; }

    /// <summary>When the link was created (UTC). DB-generated default.</summary>
    public DateTime CreatedAt { get; set; }
}
