using System.Text.RegularExpressions;

namespace CarPosAPI.Data.SchemaSync;

/// <summary>
/// Compares the live schema against the source-code schema and reports every
/// difference. Pure: it makes no decision about what to do, which is
/// <see cref="DriftDdlGenerator"/>'s job, and it touches no database.
///
/// <para>
/// The one piece of judgement it does exercise is the <em>source-owned</em> check.
/// A table or column can be missing from the EF model and still be entirely
/// intentional, because a migration created it with raw SQL — <c>positions.location</c>
/// is generated by <c>ALTER TABLE ... ADD COLUMN location geography(Point,4326)
/// GENERATED ALWAYS AS ...</c> in <c>InitialCreate</c>. Reporting that as a stray
/// column would invite an operator to drop a column the source deliberately created.
/// So the comparer is handed the full migration script and treats any object the
/// source's own SQL mentions as source-owned: still reported, never proposed for
/// deletion.
/// </para>
/// </summary>
internal static partial class SchemaComparer
{
    /// <summary>
    /// Store types that name the same PostgreSQL type. <c>format_type()</c> and EF
    /// agree in almost every case, which is why this list is short — it exists for
    /// the handful where a migration wrote an alias and the catalog echoes the
    /// canonical spelling, and it stops those showing up as a permanent, unfixable
    /// "difference" that an operator would learn to ignore.
    /// </summary>
    private static readonly Dictionary<string, string> TypeAliases = new(StringComparer.OrdinalIgnoreCase)
    {
        ["int4"] = "integer",
        ["int"] = "integer",
        ["int8"] = "bigint",
        ["int2"] = "smallint",
        ["bool"] = "boolean",
        ["float8"] = "double precision",
        ["float4"] = "real",
        ["varchar"] = "character varying",
        ["char"] = "character",
        ["timestamp"] = "timestamp without time zone",
        ["timestamptz"] = "timestamp with time zone",
        ["timetz"] = "time with time zone",
        ["uuid"] = "uuid",
    };

    /// <summary>Compares the two schemas.</summary>
    /// <param name="expected">What the source model describes.</param>
    /// <param name="actual">What the database currently has.</param>
    /// <param name="fullMigrationScript">The SQL of every migration in the source,
    /// used only for the source-owned check described on the class.</param>
    /// <returns>Every difference found, in a stable order (tables alphabetically,
    /// then columns) so two runs of the report can be compared by eye.</returns>
    public static IReadOnlyList<SchemaDifference> Compare(
        IReadOnlyDictionary<string, SchemaTable> expected,
        IReadOnlyDictionary<string, SchemaTable> actual,
        string fullMigrationScript)
    {
        List<SchemaDifference> differences = new List<SchemaDifference>();

        foreach (string tableName in expected.Keys.OrderBy(static name => name, StringComparer.Ordinal))
        {
            SchemaTable expectedTable = expected[tableName];

            if (!actual.TryGetValue(tableName, out SchemaTable? actualTable))
            {
                differences.Add(new SchemaDifference(
                    SchemaDifferenceKind.MissingTable, tableName, null, "present", null));
                continue;
            }

            CompareColumns(expectedTable, actualTable, fullMigrationScript, differences);
        }

        foreach (string tableName in actual.Keys.OrderBy(static name => name, StringComparer.Ordinal))
        {
            if (expected.ContainsKey(tableName))
            {
                continue;
            }

            differences.Add(new SchemaDifference(
                SchemaDifferenceKind.ExtraTable, tableName, null, null, "present",
                SourceOwnedNote: DescribeSourceOwnership(fullMigrationScript, tableName)));
        }

        return differences;
    }

    /// <summary>Compares one table's columns in both directions.</summary>
    /// <param name="expected">The model's version of the table.</param>
    /// <param name="actual">The database's version of the table.</param>
    /// <param name="fullMigrationScript">Migration SQL, for the source-owned check.</param>
    /// <param name="differences">Accumulator the findings are appended to.</param>
    private static void CompareColumns(
        SchemaTable expected,
        SchemaTable actual,
        string fullMigrationScript,
        List<SchemaDifference> differences)
    {
        foreach (string columnName in expected.Columns.Keys.OrderBy(static name => name, StringComparer.Ordinal))
        {
            SchemaColumn expectedColumn = expected.Columns[columnName];

            if (!actual.Columns.TryGetValue(columnName, out SchemaColumn? actualColumn))
            {
                differences.Add(new SchemaDifference(
                    SchemaDifferenceKind.MissingColumn, expected.Name, columnName,
                    expectedColumn.StoreType, null));
                continue;
            }

            if (!TypesMatch(expectedColumn.StoreType, actualColumn.StoreType))
            {
                differences.Add(new SchemaDifference(
                    SchemaDifferenceKind.TypeMismatch, expected.Name, columnName,
                    expectedColumn.StoreType, actualColumn.StoreType));
            }

            if (expectedColumn.IsNullable != actualColumn.IsNullable)
            {
                differences.Add(new SchemaDifference(
                    SchemaDifferenceKind.NullabilityMismatch, expected.Name, columnName,
                    expectedColumn.IsNullable ? "nullable" : "NOT NULL",
                    actualColumn.IsNullable ? "nullable" : "NOT NULL"));
            }
        }

        foreach (string columnName in actual.Columns.Keys.OrderBy(static name => name, StringComparer.Ordinal))
        {
            if (expected.Columns.ContainsKey(columnName))
            {
                continue;
            }

            SchemaColumn actualColumn = actual.Columns[columnName];

            // A generated column is source-owned by construction: EF's model never
            // contains one, and no data of its own is lost or gained by its
            // presence — it is derived from columns that are in the model.
            string? sourceOwned = actualColumn.IsGenerated
                ? "database-generated column, created by migration SQL outside the EF model"
                : DescribeSourceOwnership(fullMigrationScript, columnName);

            differences.Add(new SchemaDifference(
                SchemaDifferenceKind.ExtraColumn, actual.Name, columnName,
                null, actualColumn.StoreType, sourceOwned));
        }
    }

    /// <summary>
    /// Decides whether an object the EF model does not know is nonetheless created
    /// by the source's own migration SQL.
    /// </summary>
    /// <param name="fullMigrationScript">SQL of every migration in the source.</param>
    /// <param name="identifier">Table or column name to look for.</param>
    /// <returns>An explanatory note when the source creates it, otherwise <c>null</c>.</returns>
    private static string? DescribeSourceOwnership(string fullMigrationScript, string identifier)
    {
        if (fullMigrationScript.Length == 0)
        {
            return null;
        }

        // Word-boundary match so "location" does not match "geolocation_id". This is
        // deliberately a broad test: its only effect is to withhold a DROP proposal,
        // so a false positive costs a manual cleanup while a false negative would
        // offer to delete something the source created. That trade is one-sided.
        if (Regex.IsMatch(fullMigrationScript, $@"\b{Regex.Escape(identifier)}\b", RegexOptions.IgnoreCase))
        {
            return "named in the source's migration SQL, so it is not a stray";
        }

        return null;
    }

    /// <summary>Compares two store types, tolerating spelling aliases and spacing.</summary>
    /// <param name="expected">The model's store type.</param>
    /// <param name="actual">The catalog's store type.</param>
    /// <returns><c>true</c> when both name the same PostgreSQL type.</returns>
    private static bool TypesMatch(string expected, string actual)
    {
        return string.Equals(Normalize(expected), Normalize(actual), StringComparison.Ordinal);
    }

    /// <summary>
    /// Reduces a store type to a canonical form: lower-cased, whitespace collapsed,
    /// no space before the modifier, and the base name resolved through
    /// <see cref="TypeAliases"/> with any modifier kept intact.
    /// </summary>
    /// <param name="storeType">The type string as written by EF or the catalog.</param>
    /// <returns>The canonical form.</returns>
    private static string Normalize(string storeType)
    {
        string trimmed = WhitespaceRun().Replace(storeType.Trim().ToLowerInvariant(), " ");

        int parenthesis = trimmed.IndexOf('(', StringComparison.Ordinal);
        string baseName = parenthesis < 0 ? trimmed : trimmed[..parenthesis].TrimEnd();
        string modifier = parenthesis < 0 ? string.Empty : trimmed[parenthesis..].Replace(" ", string.Empty, StringComparison.Ordinal);

        if (TypeAliases.TryGetValue(baseName, out string? canonical))
        {
            baseName = canonical;
        }

        return baseName + modifier;
    }

    /// <summary>Matches any run of whitespace, for collapsing it to a single space.</summary>
    /// <returns>The compiled regex.</returns>
    [GeneratedRegex(@"\s+")]
    private static partial Regex WhitespaceRun();
}
